AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo cfn-response Lambda Layer
Resources:
  CustomS3BucketSync:
    Type: Custom::S3Bucket
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CustomSyncProvider
        - Arn
      BucketName:
        Fn::Sub: demo-cfn-bucket-${AWS::AccountId}-sync5
  CustomS3BucketAsync:
    Type: Custom::S3Bucket
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - CustomAsyncProvider
        - Arn
      BucketName:
        Fn::Sub: demo-cfn-bucket-${AWS::AccountId}-async3
  CustomSyncProvider:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/3978cb347c9d8cbdc08b5c6f1c633c33
      Handler: index.handler
      Runtime: nodejs10.x
      Layers:
      - Ref: CloudFormationResponseLayer
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:CreateBucket
          - s3:DeleteBucket
          Resource:
          - Fn::Sub: arn:aws:s3:::demo-cfn-bucket-${AWS::AccountId}-*
  CustomAsyncProvider:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://werberm-sandbox/7bbb7c86a9130f17ffe3a8dda3e81273
      Handler: index.handler
      Runtime: nodejs10.x
      Layers:
      - Ref: CloudFormationResponseLayer
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:CreateBucket
          - s3:DeleteBucket
          Resource:
          - Fn::Sub: arn:aws:s3:::demo-cfn-bucket-${AWS::AccountId}-*
  CloudFormationResponseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: node10-cfn-response
      Description: Contains a sync and async helper function to send responses to
        CloudFormation for custom resources
      ContentUri: s3://werberm-sandbox/4382fb5f1dae548f184693a6cdfdb73f
      CompatibleRuntimes:
      - nodejs10.x
      LicenseInfo: MIT
      RetentionPolicy: Retain
